version: '3.4'

services:
  package-repo:
    image: danesparza/package-assistant:1.1.30
    container_name: package-assist
    tty: true
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PACKASSIST_UPLOAD_PATH=${PACKASSIST_UPLOAD_PATH}
      - PACKASSIST_GITHUB_PROJECTFOLDER=${PACKASSIST_GITHUB_PROJECTFOLDER}
      - PACKASSIST_GITHUB_PROJECTURL=${PACKASSIST_GITHUB_PROJECTURL}
      - PACKASSIST_GITHUB_USER=${PACKASSIST_GITHUB_USER}
      - PACKASSIST_GITHUB_PASSWORD=${PACKASSIST_GITHUB_PASSWORD}
      - PACKASSIST_GPG_KEY=${PACKASSIST_GPG_KEY}
      - PACKASSIST_GPG_PASSWORD=${PACKASSIST_GPG_PASSWORD}
      - PACKASSIST_AUTH_TOKEN=${PACKASSIST_AUTH_TOKEN}
    volumes: # Change the first part of the path to match the environment
      - /Users/danesparza/package-assistant:/data/
    ports:
      - "8080:8080"